services:
  - type: web
    name: blockinspector
    env: python
    plan: free
    buildCommand: "pip install --no-cache-dir -r requirements.txt"
    startCommand: "python app.py"
    envVars:
      - key: PYTHONUNBUFFERED
        value: "1"
